// Clone OS — Provenance Classifier (N1.1)
//
// Provenance classification happens DURING extraction, not deferred to export.
// This is the critical distinction: the clone must never have an inseparable
// knowledge store by the time you try to enforce ownership.
//
// The classifier uses keyword heuristics + the LLM's classification (the
// extraction prompt asks the LLM to classify). The keyword heuristics are a
// safety net — if the LLM says "user_general" but the text mentions a specific
// company's proprietary formula, the heuristic overrides to company_proprietary.

export type ProvenanceKind =
  | 'user_general'
  | 'company_proprietary'
  | 'client_data'
  | 'public'
  | 'licensed'
  | 'third_party'
  | 'generated'

export interface ProvenanceClassification {
  kind: ProvenanceKind
  sensitivity: 'public' | 'internal' | 'confidential' | 'restricted'
  portability: 'portable' | 'tenant_locked' | 'client_locked'
  reason: string
}

// Keyword heuristics — if these patterns appear, the provenance is overridden.
const COMPANY_PATTERNS = [
  /\b(at|our|my)\s+(company|org|employer|firm)\b/i,
  /\b(our|my)\s+(proprietary|confidential|internal)\s+(formula|process|method|IP|knowledge)\b/i,
  /\b(company|employer)\s+(A|B|C|[A-Z][a-z]+)\s+(proprietary|confidential)\b/i,
  /\b(NDA|non-disclosure|confidential)\b/i,
]

const CLIENT_PATTERNS = [
  /\b(client|customer)\s+(X|Y|Z|[A-Z][a-z]+)\b/i,
  /\b(client|customer)\s+(data|report|file|document|information)\b/i,
  /\b(confidential\s+client|client\s+confidential)\b/i,
  /\b(under\s+NDA|under\s+contract)\b/i,
]

const PUBLIC_PATTERNS = [
  /\b(public|published|well-known|industry\s+standard|best\s+practice)\b/i,
  /\b(B2B\s+SaaS|SaaS|CRM|RevOps)\b/i, // common industry terms
]

const LICENSED_PATTERNS = [
  /\b(licensed|license|royalty|permitted)\b/i,
]

export function classifyProvenance(
  text: string,
  llmClassification?: string,
): ProvenanceClassification {
  // If the LLM classified, use it as a starting point
  let kind: ProvenanceKind = (llmClassification as ProvenanceKind) || 'user_general'

  // Keyword override: company_proprietary takes priority
  if (COMPANY_PATTERNS.some((p) => p.test(text))) {
    kind = 'company_proprietary'
  } else if (CLIENT_PATTERNS.some((p) => p.test(text))) {
    kind = 'client_data'
  } else if (LICENSED_PATTERNS.some((p) => p.test(text))) {
    kind = 'licensed'
  } else if (PUBLIC_PATTERNS.some((p) => p.test(text)) && kind === 'user_general') {
    kind = 'public'
  }

  // Map kind → sensitivity + portability
  switch (kind) {
    case 'user_general':
      return { kind, sensitivity: 'internal', portability: 'portable', reason: 'User\'s general professional expertise' }
    case 'company_proprietary':
      return { kind, sensitivity: 'confidential', portability: 'tenant_locked', reason: 'Mentions a specific company\'s proprietary process/formula/IP' }
    case 'client_data':
      return { kind, sensitivity: 'restricted', portability: 'client_locked', reason: 'Mentions a specific client\'s confidential data' }
    case 'public':
      return { kind, sensitivity: 'public', portability: 'portable', reason: 'Publicly known industry knowledge' }
    case 'licensed':
      return { kind, sensitivity: 'internal', portability: 'tenant_locked', reason: 'Licensed knowledge (under license terms)' }
    case 'third_party':
      return { kind, sensitivity: 'internal', portability: 'tenant_locked', reason: 'Third-party data (under third-party terms)' }
    case 'generated':
      return { kind, sensitivity: 'internal', portability: 'portable', reason: 'Generated by the platform' }
  }
}

export const PROVENANCE_LABELS: Record<ProvenanceKind, string> = {
  user_general: "User's General Expertise",
  company_proprietary: 'Company Proprietary',
  client_data: 'Client Data',
  public: 'Public Knowledge',
  licensed: 'Licensed Knowledge',
  third_party: 'Third-Party Data',
  generated: 'Generated Knowledge',
}
